require("nvim-treesitter").setup({
	install_dir = vim.fn.stdpath("data") .. "/site",
	ensure_installed = {
		"lua",
		"vim",
		"vimdoc",
		"bash",
		"html",
		"css",
		"javascript",
		"typescript",
		"tsx",
		"json",
		"php",
		"markdown",
		"markdown_inline",
	},
	auto_install = true,
	sync_install = false,
})
