# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 14.0

# Ligature
font_features JetBrainsMonoNF-Regular +liga +calt
font_features JetBrainsMonoNF-Bold +liga +calt
font_features JetBrainsMonoNF-Italic +liga +calt
font_features JetBrainsMonoNF-BoldItalic +liga +calt

# Window
window_padding_width 10
background_opacity 0.9
confirm_os_window_close 0

allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}
hide_window_decorations yes
wayland_titlebar_color background

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Scroll history
scrollback_lines 10000

# URL
detect_urls yes

include colors.conf
