# Font
font_family      IBM Plex Mono
font_size        14.0

# Window
window_padding_width 10
background_opacity 0.9
confirm_os_window_close 0

allow_remote_control yes
listen_on unix:/tmp/kitty

include colors.conf
