[config]
version_check = false

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.mako]
input_path = '~/.config/matugen/templates/mako.conf'
output_path = '~/.config/mako/config'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.config/tmux/conf/status.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
