# ===================================
# Foot terminal configuration
# ===================================
include=/home/xxx/.config/foot/colors.ini

[main]
term=xterm-256color
font=IBM Plex Mono:size=14
dpi-aware=yes
pad=6x6
bold-text-in-bright=no
selection-target=clipboard

[cursor]
style=underline
blink=yes

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000

[url]
launch=xdg-open ${url}
