"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[╭─](fg:#928374)\
$os\
$username\
[](fg:#504945 bg:#3c3836)\
$directory\
[](fg:#3c3836 bg:#504945)\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
[](fg:#504945)\
$fill\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$package\
[](fg:#504945)\
$docker_context\
$kubernetes\
[](fg:#504945 bg:#3c3836)\
$cmd_duration\
$jobs\
$battery\
$time\
[](fg:#3c3836)\
$line_break\
[╰─](fg:#928374)$character\
"""

palette = 'gruvbox'
scan_timeout = 3600
command_timeout = 3600

[palettes.gruvbox]
bg0 = '#282828'
bg1 = '#3c3836'
bg2 = '#504945'
bg3 = '#665c54'
fg = '#ebdbb2'
red = '#cc241d'
orange = '#d65d0e'
yellow = '#d79921'
green = '#98971a'
aqua = '#689d6a'
blue = '#458588'
purple = '#b16286'
grey = '#928374'

[fill]
symbol = " "

[os]
disabled = false
style = "fg:blue bg:bg1"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = "󱘊"
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
CachyOS = ""
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bold fg:aqua bg:bg1"
style_root = "bold fg:red bg:bg1"
format = '[$user ]($style)'

[directory]
style = "bold fg:fg bg:bg1"
read_only_style = "fg:red bg:bg1"
repo_root_style = "bold fg:yellow bg:bg1"
format = "[ $path ]($style)[$read_only]($read_only_style)"
read_only = " 󰌾 "
home_symbol = "~"
truncation_symbol = "…/"
truncation_length = 3
truncate_to_repo = true
use_logical_path = true

[git_branch]
symbol = ""
style = "bold fg:blue bg:bg2"
format = '[ $symbol $branch ]($style)'
only_attached = false
truncation_length = 20
truncation_symbol = "…"
disabled = false

[git_commit]
style = "fg:blue bg:bg2"
format = '[ @$hash$tag ]($style)'
commit_hash_length = 7
only_detached = true
tag_symbol = " 󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:aqua bg:bg2"
format = '([$all_status$ahead_behind ]($style))'
stashed = "󰏖 $count "
ahead = "⇡$count "
behind = "⇣$count "
up_to_date = ""
diverged = "⇕⇡$ahead_count⇣$behind_count "
conflicted = "=$count "
deleted = "✘ $count "
renamed = "» $count "
modified = "● $count "
staged = "+$count "
untracked = "?$count "
disabled = false

[git_metrics]
format = '[+$added]($added_style)[-$deleted]($deleted_style) '
added_style = "fg:green bg:bg2"
deleted_style = "fg:red bg:bg2"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "bold fg:red bg:bg2"
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
disabled = false

[c]
symbol = ""
style = "fg:blue bg:bg2"
format = '[ $symbol $version ]($style)'

[rust]
symbol = "󱘗"
style = "fg:orange bg:bg2"
format = '[ $symbol $version ]($style)'

[golang]
symbol = "󰟓"
style = "fg:blue bg:bg2"
format = '[ $symbol $version ]($style)'

[nodejs]
symbol = ""
style = "fg:green bg:bg2"
format = '[ $symbol $version ]($style)'

[php]
symbol = ""
style = "fg:purple bg:bg2"
format = '[ $symbol $version ]($style)'

[java]
symbol = ""
style = "fg:red bg:bg2"
format = '[ $symbol $version ]($style)'

[kotlin]
symbol = ""
style = "fg:purple bg:bg2"
format = '[ $symbol $version ]($style)'

[haskell]
symbol = ""
style = "fg:purple bg:bg2"
format = '[ $symbol $version ]($style)'

[python]
symbol = ""
style = "fg:yellow bg:bg2"
format = '[ $symbol $version ]($style)'

[lua]
symbol = ""
style = "fg:blue bg:bg2"
format = '[ $symbol $version ]($style)'

[package]
symbol = "󰏗"
style = "fg:aqua bg:bg2"
format = '[ $symbol $version ]($style)'
disabled = false

[docker_context]
symbol = ""
style = "fg:blue bg:bg2"
format = '[ $symbol $context ]($style)'

[kubernetes]
symbol = "󱃾"
style = "fg:aqua bg:bg2"
format = '[ $symbol $context/$cluster ]($style)'
disabled = false

[jobs]
symbol = "󰒋"
style = "bold fg:orange bg:bg1"
format = '[ $symbol $number ]($style)'
symbol_threshold = 1
number_threshold = 1

[battery]
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰂃"
unknown_symbol = "󰂑"
empty_symbol = "󰂎"
format = '[$symbol $percentage ]($style)'
disabled = false

[[battery.display]]
threshold = 15
style = "bold fg:red bg:bg1"

[[battery.display]]
threshold = 30
style = "bold fg:yellow bg:bg1"

[[battery.display]]
threshold = 100
style = "fg:green bg:bg1"

[time]
disabled = false
time_format = "%H:%M"
style = "fg:fg bg:bg1"
format = '[ 󰥔 $time ]($style)'

[cmd_duration]
min_time = 1000
format = '[ 󱫑 $duration ]($style)'
style = 'bold fg:yellow bg:bg1'
show_milliseconds = false
disabled = false

[status]
disabled = false
format = '[ $symbol$common_meaning$signal_name ]($style)'
map_symbol = true
pipestatus = true
symbol = '✗ '
success_symbol = ''
not_executable_symbol = '🚫 '
not_found_symbol = '󰍉 '
sigint_symbol = '󰐊 '
signal_symbol = '󱐋 '
style = 'bold fg:red bg:bg1'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'
