# Default colors
[colors.primary]
foreground = '#C2C2C2'
background = '#333333'

[colors.normal]
black   = '#333333'
red     = '#CCCCCC'
green   = '#686868'
yellow  = '#7C7C7C'
blue    = '#868686'
magenta = '#5E5E5E'
cyan    = '#B8B8B8'
white   = '#A4A4A4'

[colors.bright]
black   = '#5E5E5E'
red     = '#333333'
green   = '#9A9A9A'
yellow  = '#868686'
blue    = '#727272'
magenta = '#AEAEAE'
cyan    = '#4A4A4A'
white   = '#7C7C7C'
