# Tmux Color Scheme - Matugen Core Colors

set -g @bg0 "{{colors.surface.default.hex}}"
set -g @bg1 "{{colors.surface_variant.default.hex}}"
set -g @bg2 "{{colors.surface_bright.default.hex}}"
set -g @bg3 "{{colors.surface_container_highest.default.hex}}"

set -g @fg "{{colors.on_surface.default.hex}}"
set -g @primary "{{colors.primary.default.hex}}"
set -g @secondary "{{colors.secondary.default.hex}}"
set -g @tertiary "{{colors.tertiary.default.hex}}"
set -g @grey0 "{{colors.outline.default.hex}}"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=#{@fg},bg=#{@bg0}"

set -g status-left-length "100"
set -g status-left "#[fg=#{@bg0},bg=#{@primary},bold] #S #[fg=#{@primary},bg=#{@secondary}]#[fg=#{@bg0},bg=#{@secondary},bold] #[fg=#{@secondary},bg=#{@tertiary}]#[fg=#{@bg0},bg=#{@tertiary}] #[fg=#{@tertiary},bg=#{@bg3}]#[fg=#{@bg3},bg=#{@bg2}]#[fg=#{@bg2},bg=#{@bg1}]#[fg=#{@bg1},bg=#{@bg0}] "

set -g status-right-length "100"
set -g status-right "#[fg=#{@bg1},bg=#{@bg0}]#[fg=#{@bg2},bg=#{@bg1}]#[fg=#{@bg3},bg=#{@bg2}]#[fg=#{@tertiary},bg=#{@bg3}] #[fg=#{@bg3},bg=#{@tertiary}]#[fg=#{@secondary},bg=#{@tertiary}]#[fg=#{@bg0},bg=#{@secondary}] %H:%M #[fg=#{@secondary},bg=#{@primary}]#[fg=#{@bg0},bg=#{@primary},bold] #H "

setw -g window-status-separator ""
setw -g window-status-format "#[fg=#{@grey0},bg=#{@bg0}]  #I #W  "
setw -g window-status-current-format "#[fg=#{@bg1},bg=#{@bg0}]#[fg=#{@bg2},bg=#{@bg1}]#[fg=#{@tertiary},bg=#{@bg2}] #[fg=#{@secondary},bg=#{@tertiary}]#[fg=#{@primary},bg=#{@secondary}]#[fg=#{@bg0},bg=#{@primary},bold] #I #W #[fg=#{@primary},bg=#{@secondary}]#[fg=#{@secondary},bg=#{@tertiary}]#[fg=#{@tertiary},bg=#{@bg2}]#[fg=#{@bg2},bg=#{@bg1}]#[fg=#{@bg1},bg=#{@bg0}]"

set -g mode-style "fg=#{@bg0},bg=#{@primary}"
set -g message-style "fg=#{@fg},bg=#{@bg2}"
set -g pane-border-style "fg=#{@bg1}"
set -g pane-active-border-style "fg=#{@primary}"
