
set -g @bg0 "{{colors.surface.default.hex}}"
set -g @bg1 "{{colors.surface_variant.default.hex}}"
set -g @bg2 "{{colors.surface_bright.default.hex}}"
set -g @bg3 "{{colors.surface_container_highest.default.hex}}"

set -g @fg "{{colors.on_surface.default.hex}}"
set -g @primary "{{colors.primary.default.hex}}"
set -g @secondary "{{colors.secondary.default.hex}}"
set -g @tertiary "{{colors.tertiary.default.hex}}"
set -g @grey0 "{{colors.outline.default.hex}}"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=#{@primary},bg=default"

set -g status-left-length "100"
set -g status-left "#[fg=#{@bg0},bg=#{@primary},bold]  #S #[fg=#{@primary},bg=default]"

set -g status-right-length "100"
set -g status-right "#[fg=#{@bg1},bg=default]#[fg=#{@fg},bg=#{@bg1}] 󰭟 #H #[fg=#{@primary},bg=#{@bg1}]#[fg=#{@bg0},bg=#{@primary},bold]  %H:%M:%S "

setw -g window-status-separator ""
setw -g window-status-format "#[fg=#{@grey0},bg=default] #I:#W "
setw -g window-status-current-format "#[fg=#{@tertiary},bg=default]#[fg=#{@bg0},bg=#{@tertiary},bold] #I:#W #[fg=#{@tertiary},bg=default]"

set -g mode-style "fg=#{@bg0},bg=#{@primary},bold"
set -g message-style "fg=#{@primary},bg=#{@bg0},bold"
set -g pane-border-style "fg=#{@bg1}"
set -g pane-active-border-style "fg=#{@primary}"

set -g status-bg default
set -g pane-border-lines "simple"
