set -as terminal-features ",foot*:sixel:RGB:usstyle"
set -as terminal-overrides ",foot*:Smul=\E[4m:rmul=\E[24m"
set -as terminal-overrides ',xterm*:Ss=\E[%p1%d q:Se=\E[ q'
set -g base-index 1
set -g default-terminal "tmux-256color"
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -g set-titles on
set -g status-position top
set -g visual-activity off
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -gq allow-passthrough on
set -sg repeat-time 500
setw -g automatic-rename on
setw -g pane-base-index 1
setw -q -g utf8 on
