set -g @bg0 "#f9f9f9"
set -g @bg1 "#e2e2e2"
set -g @bg2 "#f9f9f9"
set -g @bg3 "#e2e2e2"
set -g @fg "#1b1b1b"
set -g @primary "#934b00"
set -g @secondary "#755945"
set -g @tertiary "#5e6135"
set -g @grey0 "#777777"
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=#{@primary},bg=default"
set -g status-left-length "100"
set -g status-left "#[fg=#{@bg0},bg=#{@primary},bold]  #S #[fg=#{@primary},bg=default]"
set -g status-right-length "100"
set -g status-right "#[fg=#{@bg1},bg=default]#[fg=#{@fg},bg=#{@bg1}]   #H #[fg=#{@primary},bg=#{@bg1}]#[fg=#{@bg0},bg=#{@primary},bold] 󰖙 %H:%M:%S "
setw -g window-status-separator ""
setw -g window-status-format "#[fg=#{@grey0},bg=default] #I:#W "
setw -g window-status-current-format "#[fg=#{@tertiary},bg=default]#[fg=#{@bg0},bg=#{@tertiary},bold] #I:#W #[fg=#{@tertiary},bg=default]"
set -g mode-style "fg=#{@bg0},bg=#{@primary},bold"
set -g message-style "fg=#{@primary},bg=#{@bg0},bold"
set -g pane-border-style "fg=#{@bg1}"
set -g pane-active-border-style "fg=#{@primary}"
set -g status-bg default
set -g pane-border-lines "simple"
