bg0="#32302f"
bg1="#3c3836"
bg2="#504945"
bg3="#665c54"
fg="#d4be98"
yellow="#d8a657"
yellow_dim="#b8963e"
yellow_dark="#9a7d2e"
green="#a9b665"
grey0="#928374"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=$fg,bg=$bg0"
set -g status-left-length "100"
set -g status-left "#[fg=$bg0,bg=$yellow,bold] #S #[fg=$yellow,bg=$yellow_dim]#[fg=$bg0,bg=$yellow_dim,bold] #[fg=$yellow_dim,bg=$yellow_dark]#[fg=$bg0,bg=$yellow_dark] #[fg=$yellow_dark,bg=$bg3]#[fg=$bg3,bg=$bg2]#[fg=$bg2,bg=$bg1]#[fg=$bg1,bg=$bg0] "
set -g status-right-length "100"
set -g status-right "#[fg=$bg1,bg=$bg0]#[fg=$bg2,bg=$bg1]#[fg=$bg3,bg=$bg2]#[fg=$yellow_dark,bg=$bg3] #[fg=$bg3,bg=$yellow_dark]#[fg=$yellow_dim,bg=$yellow_dark]#[fg=$bg0,bg=$yellow_dim] %H:%M #[fg=$yellow_dim,bg=$yellow]#[fg=$bg0,bg=$yellow,bold] #H "
setw -g window-status-separator ""
setw -g window-status-format "#[fg=$grey0,bg=$bg0]  #I #W  "
setw -g window-status-current-format "#[fg=$bg1,bg=$bg0]#[fg=$bg2,bg=$bg1]#[fg=$yellow_dark,bg=$bg2] #[fg=$yellow_dim,bg=$yellow_dark]#[fg=$yellow,bg=$yellow_dim]#[fg=$bg0,bg=$yellow,bold] #I #W #[fg=$yellow,bg=$yellow_dim]#[fg=$yellow_dim,bg=$yellow_dark]#[fg=$yellow_dark,bg=$bg2]#[fg=$bg2,bg=$bg1]#[fg=$bg1,bg=$bg0]"
set -g mode-style "fg=$bg0,bg=$yellow"
set -g message-style "fg=$fg,bg=$bg2"
set -g pane-border-style "fg=$bg1"
set -g pane-active-border-style "fg=$yellow"
