bg0="#282828"
bg1="#3c3836"
bg2="#504945"
fg="#ebdbb2"
blue="#83a598"
aqua="#8ec07c"
green="#b8bb26"
yellow="#fabd2f"
purple="#d3869b"
grey0="#928374"
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=$fg,bg=$bg0"
set -g status-left-length "100"
set -g status-left "#[fg=$bg0,bg=$blue,bold] #S #[fg=$blue,bg=$aqua] #[fg=$aqua,bg=$green] #[fg=$green,bg=$bg0] "
set -g status-right-length "100"
set -g status-right "#[fg=$grey0,bg=$bg0] %d/%m #[fg=$bg1,bg=$bg0] #[fg=$fg,bg=$bg1] %H:%M #[fg=$bg2,bg=$bg1] #[fg=$yellow,bg=$bg2,bold] #H "
setw -g window-status-separator ""
setw -g window-status-format "#[fg=$grey0,bg=$bg0]  #I #W  "
setw -g window-status-current-format "#[fg=$bg1,bg=$bg0] #[fg=$bg2,bg=$bg1] #[fg=$aqua,bg=$bg2,bold] #I #W #[fg=$bg2,bg=$bg1] #[fg=$bg1,bg=$bg0] "
set -g mode-style "fg=$bg0,bg=$blue"
set -g message-style "fg=$fg,bg=$bg2"
set -g pane-border-style "fg=$bg1"
set -g pane-active-border-style "fg=$aqua"
