require("core.options")
require("core.keymaps")
require("core.autocmds")
require("core.colorscheme")

require("plugins.mini")
require("plugins.cmp")
require("plugins.lsp")
require("plugins.format")
require("plugins.statusline")
